pool:
  vmImage: 'windows-latest'

pr:
  drafts: false

jobs:
  - job: Build
    steps:
      - checkout: self
        submodules: recursive

      - task: DotNetCoreCLI@2
        displayName: '.NET Build'
        inputs:
          command: 'publish'
          projects: |
            **/Eevee.Sleep.Bot.csproj
          publishWebProjects: False
          arguments: >
            --output "$(Build.ArtifactStagingDirectory)" 
            --runtime win-x64 
            --configuration Release 
            --self-contained true 
            -p:PublishSingleFile=true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Eevee.Sleep.Artifact'
          publishLocation: 'Container'
